//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 01:49:56 AM AST 
//


package by.epam.jamp.module15.web.soap.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.epam.jamp.module15.web.soap.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.epam.jamp.module15.web.soap.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdatePersonSoapRequest }
     * 
     */
    public UpdatePersonSoapRequest createUpdatePersonSoapRequest() {
        return new UpdatePersonSoapRequest();
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPersonDto() {
        return new PersonDto();
    }

    /**
     * Create an instance of {@link DeletePersonSoapResponse }
     * 
     */
    public DeletePersonSoapResponse createDeletePersonSoapResponse() {
        return new DeletePersonSoapResponse();
    }

    /**
     * Create an instance of {@link UpdatePersonSoapResponse }
     * 
     */
    public UpdatePersonSoapResponse createUpdatePersonSoapResponse() {
        return new UpdatePersonSoapResponse();
    }

    /**
     * Create an instance of {@link GetAllPersonSoapResponse }
     * 
     */
    public GetAllPersonSoapResponse createGetAllPersonSoapResponse() {
        return new GetAllPersonSoapResponse();
    }

    /**
     * Create an instance of {@link DeleteAllPersonSoapResponse }
     * 
     */
    public DeleteAllPersonSoapResponse createDeleteAllPersonSoapResponse() {
        return new DeleteAllPersonSoapResponse();
    }

    /**
     * Create an instance of {@link CreatePersonSoapResponse }
     * 
     */
    public CreatePersonSoapResponse createCreatePersonSoapResponse() {
        return new CreatePersonSoapResponse();
    }

    /**
     * Create an instance of {@link GetAllPersonSoapRequest }
     * 
     */
    public GetAllPersonSoapRequest createGetAllPersonSoapRequest() {
        return new GetAllPersonSoapRequest();
    }

    /**
     * Create an instance of {@link GetPersonSoapRequest }
     * 
     */
    public GetPersonSoapRequest createGetPersonSoapRequest() {
        return new GetPersonSoapRequest();
    }

    /**
     * Create an instance of {@link CreatePersonSoapRequest }
     * 
     */
    public CreatePersonSoapRequest createCreatePersonSoapRequest() {
        return new CreatePersonSoapRequest();
    }

    /**
     * Create an instance of {@link DeleteAllPersonSoapRequest }
     * 
     */
    public DeleteAllPersonSoapRequest createDeleteAllPersonSoapRequest() {
        return new DeleteAllPersonSoapRequest();
    }

    /**
     * Create an instance of {@link DeletePersonSoapRequest }
     * 
     */
    public DeletePersonSoapRequest createDeletePersonSoapRequest() {
        return new DeletePersonSoapRequest();
    }

    /**
     * Create an instance of {@link GetPersonSoapResponse }
     * 
     */
    public GetPersonSoapResponse createGetPersonSoapResponse() {
        return new GetPersonSoapResponse();
    }

}
